### ISSUE TITLE
[laserscan_multi_merger-1] process has died [pid 9227, exit code -11

### ISSUE THREAD

**Issue by Julius-ZCJ** [zhangzhouyuan/laser_fuse#1]
你好，我在参考本项目的代码，使用ira_laser_tools融合两个雷达的数据，但是出现错误：

[laserscan_multi_merger-1] process has died [pid 9227, exit code -11, cmd /home/julius/work_space/project/catkin_chache_ws/devel/lib/ira_laser_tools/laserscan_multi_merger __name:=laserscan_multi_merger __log:=/home/julius/.ros/log/da39b41c-5316-11ec-8963-c858c0935ed6/laserscan_multi_merger-1.log].
log file: /home/julius/.ros/log/da39b41c-5316-11ec-8963-c858c0935ed6/laserscan_multi_merger-1*.log

想请教大佬有没有遇到类似的问题，怎么解决这个问题。

**Comment by zhangzhouyuan** [comment]
查看/home/julius/.ros/log/da39b41c-5316-11ec-8963-c858c0935ed6/laserscan_multi_merger-1.log日志文件，看具体出现什么错误

**Comment by Julius-ZCJ** [comment]
> 查看/home/julius/.ros/log/da39b41c-5316-11ec-8963-c858c0935ed6/laserscan_multi_merger-1.log日志文件，看具体出现什么错误

![Screenshot 2021-12-02 14:36:30](https://user-images.githubusercontent.com/42171296/144370573-d6f420d2-2e1f-425a-bba9-43d3a747ebfb.png)
没有这个log文件，这怎么办

**Comment by zhangzhouyuan** [comment]
你打开的文件旧不对，肯定没有呀

**Comment by Julius-ZCJ** [comment]
> 你打开的文件旧不对，肯定没有呀

我打开da39b41c-5316-11ec-8963-c858c0935ed6目录也还是一样的没有，目录不对因为我运行了多次，这只是其中的一次，但是结果都是一样的没有

**Comment by zhangzhouyuan** [comment]
process has died 上面还有内容吧，放全了

**Comment by Julius-ZCJ** [comment]
> process has died 上面还有内容吧，放全了

... logging to /home/julius/.ros/log/0c3a4e78-5339-11ec-8963-c858c0935ed6/roslaunch-julius-ROG-17994.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:36567/

SUMMARY
========

PARAMETERS
 * /laserscan_multi_merger/angle_increment: 0.0
 * /laserscan_multi_merger/angle_max: 3.0
 * /laserscan_multi_merger/angle_min: -3.0
 * /laserscan_multi_merger/cloud_destination_topic: /merged_cloud
 * /laserscan_multi_merger/destination_frame: base_link
 * /laserscan_multi_merger/laserscan_topics: /scan1  /scan2
 * /laserscan_multi_merger/range_max: 6.0
 * /laserscan_multi_merger/range_min: 0.1
 * /laserscan_multi_merger/scan_destination_topic: /scan_multi
 * /laserscan_multi_merger/scan_time: 0.0
 * /rosdistro: melodic
 * /rosversion: 1.14.12

NODES
  /
    laserscan_multi_merger (ira_laser_tools/laserscan_multi_merger)

ROS_MASTER_URI=http://localhost:11311

process[laserscan_multi_merger-1]: started with pid [18024]
[ INFO] [1638427185.770625036]: Subscribing to topics	2
[laserscan_multi_merger-1] process has died [pid 18024, exit code -11, cmd /home/julius/work_space/project/catkin_chache_ws/devel/lib/ira_laser_tools/laserscan_multi_merger __name:=laserscan_multi_merger __log:=/home/julius/.ros/log/0c3a4e78-5339-11ec-8963-c858c0935ed6/laserscan_multi_merger-1.log].
log file: /home/julius/.ros/log/0c3a4e78-5339-11ec-8963-c858c0935ed6/laserscan_multi_merger-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
这是全的

**Comment by zhangzhouyuan** [comment]
没建立tf关系吧

**Comment by Julius-ZCJ** [comment]
您好，我现在已经弄好了，是我参数设置出现问题，导致程序出现问题，通过排查已经改正。非常感谢您的帮助
